//Try...Catch Statement

//The try...catch statement is used to handle exceptions in JavaScript. 
// The code inside the try block is executed, and if an error occurs, the code inside the catch block will handle the error.

//the whole point of try...catch ðŸ‘‰ execution continues instead of stopping.

// Without try...catch:

// Error happens â†’ program crashes â†’ nothing after the error runs.

// With try...catch:

// Error happens â†’ caught in catch â†’ you decide what to do (log it, retry, fallback, etc.) â†’ program keeps running after the try...catch.

try{
    let result = someUndefinedFunction();// This will throw an error
    console.log(result);
}catch(error){
    console.error("An error occurred: ", error.message)
}